### ISSUE TITLE
Error on Android Lollipop

### ISSUE THREAD

**Issue by oms064** [adrianstevens/Xamarin-Plugins#31] opened 2018-07-09 06:40 UTC
Hello.
I am getting a Java.Lang.IllegalStateException only on Android Lollipop (5 and 5.1).

I am playing a sound for each tap the user makes on the screen so it can play many times consecutively. I first thought I had to check if the sound was already playing before calling Play but the error still occurs.

This is the callstack:

 - 0xFFFFFFFFFFFFFFFF in System.Diagnostics.Debugger.Mono_UnhandledException_internal
 - 0x1 in System.Diagnostics.Debugger.Mono_UnhandledException
 - 0x26 in object.2708d655-fbb7-47fd-8eb7-e115d7fca965
 - 0x12 in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
 - 0x69 in Java.Interop.JniEnvironment.InstanceMethods.CallVoidMethod
 - 0x2C in Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod
 - 0x12 in Android.Media.MediaPlayer.Prepare
 - 0x39 in Plugin.SimpleAudioPlayer.SimpleAudioPlayerImplementation.OnPlaybackEnded at F:\dev\open\Xamarin-Plugins\SimpleAudioPlayer\SimpleAudioPlayer\Plugin.SimpleAudioPlayer.Android\SimpleAudioPlayerImplementation.cs:240,17
 - 0x11 in Android.Media.MediaPlayer.IOnCompletionListenerImplementor.OnCompletion
 - 0x11 in Android.Media.MediaPlayer.IOnCompletionListenerInvoker.n_OnCompletion_Landroid_media_MediaPlayer_
 - 0x17 in object.2708d655-fbb7-47fd-8eb7-e115d7fca965

**Comment by Stenciletto** [comment] 2018-07-25 09:21
I have found this as well. The cause is 'player.Prepare();' in 'OnPlaybackEnded', it's throwing an IllegalStateException. Comment out this line and it works OK.

**Comment by BioTurboNick** [comment] 2018-08-07 14:26
I get the same exception, only I never use OnPlaybackEnded or Prepare.

**Comment by BioTurboNick** [comment] 2018-08-08 03:37
I'm guessing it is because of the lines in OnPlaybackEnded() which invokes player.Prepare() on Lollipop and below.

It appears these lines were added to address some other crashes on older devices. First it was added for all devices, then restricted to Lollipop and below.

Should the code perhaps be restricted to < Lollipop instead of < Marshmallow? Looking back at the history, the bug that led to this code being introduced (#5) was in KitKat. If that bug did not exist in Lollipop, then this change may be the answer. @adrianstevens what do you think?

**Comment by devkev2403** [comment] 2019-03-13 10:08
I also have this issue and am currently investigating further.  Has any progress been made on this?

**Comment by BioTurboNick** [comment] 2019-03-13 12:10
I believe I can confirm that the change I suggested works to reduce crashes on Lollipop. I do have a similar lllegalStateException now on Jelly Bean (4.3) just reported, however.

**Comment by devkev2403** [comment] 2019-03-13 12:52
Thanks - are there any plans to introduce that code fix in to the main branch?

**Comment by adrianstevens** [comment] 2019-07-25 01:57
Thank you everyone! - the changes have be merged and are included in the latest version 

Closing issue

**Closed by adrianstevens** 2019-07-25 01:57 UTC
