### ISSUE TITLE
No Playback Ended callback if Siri is activated

### ISSUE THREAD

**Issue by chrisfoulds** [adrianstevens/Xamarin-Plugins#74] opened 2020-07-21 09:50 UTC
If you activate Siri when an audio message is playing PlaybackEnded is never called.

**Comment by chrisfoulds** [comment] 2020-07-21 10:23
https://developer.apple.com/documentation/avfoundation/avaudioplayerdelegate/1389160-audioplayerdidfinishplaying
Audio is interrupted but no callback to inform the main app is available.

**Comment by adrianstevens** [comment] 2022-04-13 05:22
since this is expected behavior I'm closing the issue

**Closed by adrianstevens** 2022-04-13 05:22 UTC
