### ISSUE TITLE
Exception of type 'Java.Lang.IllegalStateException' was thrown.

### ISSUE THREAD

**Issue by K232** [adrianstevens/Xamarin-Plugins#54] opened 2019-05-31 06:52 UTC
First: Thanks a lot for this plugin! In most cases it works really fine.

But unfortunately, my app occasionally crashes with this error reported in AppCenter:

```
SimpleAudioPlayerImplementation.OnPlaybackEnded (System.Object sender, System.EventArgs e)
Java.Lang.IllegalStateException: Exception of type 'Java.Lang.IllegalStateException' was thrown.

    JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args)
    JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
    MediaPlayer.Prepare ()
    SimpleAudioPlayerImplementation.OnPlaybackEnded (System.Object sender, System.EventArgs e)
    MediaPlayer+IOnCompletionListenerImplementor.OnCompletion (Android.Media.MediaPlayer mp)
    MediaPlayer+IOnCompletionListenerInvoker.n_OnCompletion_Landroid_media_MediaPlayer_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_mp)
    (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.100(intptr,intptr,intptr)
    java.lang.IllegalStateException
    android.media.MediaPlayer._prepare(Native Method)
    android.media.MediaPlayer.prepare(MediaPlayer.java:1135)
    mono.android.media.MediaPlayer_OnCompletionListenerImplementor.n_onCompletion(Native Method)
    mono.android.media.MediaPlayer_OnCompletionListenerImplementor.onCompletion(MediaPlayer_OnCompletionListenerImplementor.java:30)
    android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:2584)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:135)
    android.app.ActivityThread.main(ActivityThread.java:5597)
    java.lang.reflect.Method.invoke(Native Method)
    java.lang.reflect.Method.invoke(Method.java:372)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```
For testing I use an Amazon Fire HD 7 with Android / FireOS 5.1.1.

I'm not able to reproduce this error. During a 2 hour app using session it appeared 4 times, roundabout every 30 minutes. So after restarting the app, it works fine again. 

I use the plugin as explained in "[Playing Multiple Sounds Simultanously](https://devblogs.microsoft.com/xamarin/adding-sound-xamarin-forms-app/)" . I do not subscribe to any events like mentioned OnPlaybackEnded.

Any ideas?

**Comment by adrianstevens** [comment] 2019-07-25 01:48
Without being able to reproduce the problem it's hard to diagnose. I see the illigal state exception so it's likely within the Android media player object.

I'll do some additional testing but unfortunately I don't own an Amazon Fire tablets.

**Comment by adrianstevens** [comment] 2019-07-25 01:51
It's possibly relate to issue #51 - if so, it should be fixed in 1.3.1

**Comment by traceyhemp12** [comment] 2019-09-06 19:04
@adrianstevens Have you looked into this issue with the Kindle? Thanks!

**Comment by adrianstevens** [comment] 2020-01-04 20:12
@traceyhemp12 I don't have a Kindle for testing. I'm going to release an update this weekend. Let's test it and see if it improves behavior.

**Comment by traceyhemp12** [comment] 2020-01-06 13:01
@adrianstevens I'm not able to test since I'm working on other projects but I will as soon as possible

**Comment by adrianstevens** [comment] 2021-07-19 19:55
closing issue due to lack of activity

**Closed by adrianstevens** 2021-07-19 19:55 UTC
